//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class investmentPlansSuggested
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public int currentAmount { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public string risk { get; set; }
        public int finalAmount { get; set; }
        public int investmentTime { get; set; }
        public int monthlyExpenses { get; set; }
        public int inflation { get; set; }
        public int returnPercentage { get; set; }
        public int fd { get; set; }
        public int mf { get; set; }
        public int equity { get; set; }
    }
}
