//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionOptions
    {
        public int Id { get; set; }
        public string QuestionId { get; set; }
        public string OptionId { get; set; }
        public string Option { get; set; }
        public string Weightage { get; set; }
    }
}
