//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class retirementPlansSuggested
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public int MonthlyExpenses { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public string risk { get; set; }
        public int finalAmount { get; set; }
        public int InvestmentTimeLeft { get; set; }
        public int MonthlyInvestment { get; set; }
        public int Inflation { get; set; }
        public int ReturnPercentage { get; set; }
        public Nullable<int> Fd { get; set; }
        public Nullable<int> Mf { get; set; }
        public Nullable<int> Equity { get; set; }
    }
}
